name: Simple CI/CD

# Trigger on every push to main branch
on:
  push:
    branches: [ main ]

# Global permissions for the workflow
permissions:
  contents: write
  packages: write

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.13.0
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libx11-dev \
          libxcursor-dev \
          libxi-dev \
          libxinerama-dev \
          libxrandr-dev \
          libgl1-mesa-dev \
          libasound2-dev
          
    - name: Build project
      run: |
        zig build -Doptimize=ReleaseFast
        
    - name: Run tests
      run: |
        zig build test
        
    - name: Package artifacts
      run: |
        mkdir -p dist
        cp zig-out/bin/zigline dist/
        cp README.md dist/
        cp CHANGELOG.md dist/ || echo "No changelog found"
        tar -czf zigline-linux-x64.tar.gz -C dist .
        
    - name: Generate version
      id: version
      run: |
        VERSION="v1.0.0-$(date +%Y%m%d)-$(git rev-parse --short HEAD)"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Generated version: $VERSION"
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.version.outputs.version }}
        name: Zigline Release ${{ steps.version.outputs.version }}
        body: |
          Automated release from main branch

          Commit: ${{ github.sha }}

          ## Changes
          - Built from latest main branch
          - Cross-platform terminal emulator written in Zig
          - Raylib-based GUI rendering

          ## Installation
          1. Download `zigline-linux-x64.tar.gz`
          2. Extract: `tar -xzf zigline-linux-x64.tar.gz`
          3. Run: `./zigline`
        files: zigline-linux-x64.tar.gz
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
